#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Harm te Molder's blog

# Short bio or description (displayed in the header)
description: My musings on pretty much anything I find interesting, occasionally in Dutch

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://avatars0.githubusercontent.com/u/8167752?s=460&v=4

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  bitcoin: https://www.binance.com/?ref=25685529 # a Bitcoin-related link, e.g. a Binance referral link like https://www.binance.com/?ref=25685529
  dribbble:
  ethereum: https://www.binance.com/?ref=25685529 # an Ethereum-related link, e.g. a Binance referral link like https://www.binance.com/?ref=25685529
  facebook:
  flickr: harmtemolder
  gmail: mail@harmtemolder.nl # your email address goes here or at outlook, probably
  goodreads: user/show/38080398-harm-te-molder # your goodreads profile, e.g. user/show/38080398-harm-te-molder
  googleplus: # anything in your profile username that comes after plus.google.com/
  github: harmtemolder
  instagram: sixwheelseast
  linkedin: harmtemolder
  outlook: mail@harmtemolder.nl # your email address goes here or at gmail, probably
  paypal: harmtemolder # your PayPal.Me name, e.g. harmtemolder
  pinterest:
  quora: profile/Harm-te-Molder # your Quora profile, e.g. profile/Harm-te-Molder
  rss: does anyone actually use RSS? # just type anything here for a working RSS icon
  stackexchange: # your stackexchange profile, e.g. "users/2158543/harm-te-molder"
  stackoverflow: users/1913230/harm-te-molder # your stackoverflow profile, e.g. "users/1913230/harm-te-molder"
  twitter:
  whatsapp: 31642696616 # international phone number without leading "+" or "00", e.g. "31642696616"
  youtube: # channel/<your_long_string> or user/<user-name>

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: harmtemolder

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics:

# Enter your Google Tag Manager container code (e.g. GTM-KCPM8VZ) to add GTM
google_tag_manager: GTM-KBQJ43

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: https://harmtemolder.nl

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:slug/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jemoji # GitHub-flavored Emoji plugin for Jekyll
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

theme: jekyll-theme-slate
